import { Inter } from "next/font/google";
import "./globals.css";
import { TotalAmountProvider } from "../context/TotalAmountContext";
import { ThemeProvider } from "../context/ThemeProvider";
import Theme from "../components/Theme";
import Header from "../components/Header";
import { Toaster } from "react-hot-toast";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark:bg-black/95  `}>
        <ThemeProvider>
          <TotalAmountProvider>
            <Theme />
            <Header />
            {children}
            <Toaster
              position="top-right"
              toastOptions={{
                loading: {
                  duration: 2000,
                },
              }}
            />
          </TotalAmountProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
